apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        profiles.grafana.com/memory.scrape: "true"
        profiles.grafana.com/memory.port: "8080"
        profiles.grafana.com/cpu.scrape: "true"
        profiles.grafana.com/cpu.port: "8080"
    spec:
      containers:
        - name: inventory-service-container
          image: ghcr.io/tdrozdowski/inventory-service-rs:1.0.11
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 3000
              path: /status/healthz
            initialDelaySeconds: 5
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /status/readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: inventory-service-config
            - secretRef:
                name: sqlx-db-secret
            - secretRef:
                name: inventory-service-jwt-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

      imagePullSecrets:
        - name: ghcr-login-secret
