apiVersion: batch/v1
kind: Job
metadata:
  name: sqlx-migrate-job
spec:
  template:
    spec:
      containers:
        - name: sqlx-migrate
          image: ghcr.io/tdrozdowski/inventory-service-migrate-rs:latest
          envFrom:
            - configMapRef:
                name: inventory-service-config
            - secretRef:
                name: sqlx-db-secret
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-login-secret
  backoffLimit: 1
