# a docker-compose file with a db service that contains a postgresql database container and configuration

version: '3.1'
services:
    db:
        image: postgres
        restart: always
        env_file:
          - database.env
        ports:
        - 5432:5432
        volumes:
        - ./data:/var/lib/postgresql/data
