# a docker-compose file with a db service that contains a postgresql database container and configuration
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-compose
    ports:
      - "3000:3000"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile-migrate
    depends_on:
      - db
    env_file:
      - .env-compose
    networks:
      - app_network

  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge