apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: your-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service-container
          image: your-image-registry/inventory-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database-url
      imagePullSecrets:
        - name: regcred