apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service-container
          image: ghcr.io/tdrozdowski/inventory-service-rs:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /status/healthz
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status/readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sqlx-db-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: inventory-service-jwt-secret
                  key: JWT_SECRET
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: inventory-service-config
                  key: RUST_LOG
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

      imagePullSecrets:
        - name: ghcr-login-secret