apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-alloy-servicemonitor
  namespace: examples
  labels:
    app: grafana-alloy
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: grafana-alloy
  endpoints:
    - port: prometheus
      interval: 15s