apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: examples
data:
  config.alloy: |
    global {
      scrape_interval = "15s"
    }

    prometheus {
      global {
        scrape_interval = "15s"
      }

      scrape_config {
        job_name = "inventory-service"
        
        kubernetes_sd_config {
          role = "pod"
        }

        relabel_config {
          source_labels = ["__meta_kubernetes_pod_label_app"]
          action = "keep"
          regex = "inventory-service"
        }

        relabel_config {
          source_labels = ["__meta_kubernetes_pod_container_port_name"]
          action = "keep"
          regex = "metrics"
        }
      }
    }

    otlp {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }
    }

    logs {
      pipeline {
        receiver = "otlp"
      }
    }

    metrics {
      pipeline {
        receivers = ["otlp"]
        exporters = ["prometheus"]
      }

      prometheus {
        endpoint = "0.0.0.0:8889"
      }
    }