apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: examples
data:
  config.alloy: |
    receivers {
      otlp {
        protocols {
          grpc {
            endpoint = "0.0.0.0:4317"
          }
          http {
            endpoint = "0.0.0.0:4318"
          }
        }
      }
    
      prometheus {
        config {
          scrape_configs {
            job_name = "inventory-service"
            kubernetes_sd_configs [
              {
                role = "pod"
              }
            ]
            relabel_configs [
              {
                source_labels = ["__meta_kubernetes_pod_label_app"]
                action = "keep"
                regex = "inventory-service"
              },
              {
                source_labels = ["__meta_kubernetes_pod_container_port_name"]
                action = "keep"
                regex = "metrics"
              }
            ]
          }
        }
      }
    }

    processors {
      batch {}
    }

    exporters {
      prometheus {
        endpoint = "0.0.0.0:8889"
      }
    }

    service {
      pipelines {
        metrics {
          receivers = ["otlp", "prometheus"]
          processors = ["batch"]
          exporters = ["prometheus"]
        }
        traces {
          receivers = ["otlp"]
          processors = ["batch"]
          exporters = []
        }
        logs {
          receivers = ["otlp"]
          processors = ["batch"]
          exporters = []
        }
      }
    } |