apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: examples
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      containers:
        - name: grafana-alloy
          image: grafana/alloy:v1.8.1
          command:
            - "/bin/sh"
            - "-c"
            - "/usr/bin/alloy run --stability.level public-preview /etc/alloy/config.alloy"
          ports:
            - containerPort: 4317  # OTLP gRPC
            - containerPort: 4318  # OTLP HTTP
            - containerPort: 8888  # Metrics
            - containerPort: 8889  # Prometheus exporter
            - containerPort: 9999  # pyroscope profiles over http
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
      volumes:
        - name: config
          configMap:
            name: grafana-alloy-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-alloy
  namespace: examples
spec:
  selector:
    app: grafana-alloy
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 8888
      targetPort: 8888
    - name: prometheus
      port: 8889
      targetPort: 8889
    - name: pyroscope
      port: 9999
      targetPort: 9999