apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-service-ingress
  namespace: examples
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: "nginx"
  rules:
    - host: lab1.local # Replace with your desired host
      http:
        paths:
          - path: /inventory-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  name: http