apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: examples
  labels:
    app: inventory-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: inventory-service